import re

with open(r'C:\Users\steevenz\MCP\mcp-codecortex\docs\guides\mcp-tools-insight.md', 'r', encoding='utf-8') as f:
    content = f.read()

# Translation dictionary for common Indonesian phrases
translations = {
    "Semua unified tool mengembalikan": "All unified tools return",
    "melalui": "via",
    "CodeCortex mendaftarkan": "CodeCortex registers",
    "di": "in",
    "Setiap tool menerima parameter": "Each tool accepts parameter",
    "ActionRouter mengarahkan ke domain service yang sesuai": "ActionRouter routes to the appropriate domain service",
    "Domain actions": "Domain actions",
    "bukan MCP tools terpisah": "are NOT separate MCP tools",
    "mereka adalah": "they are",
    "action string yang dipass ke salah satu 6 unified tool di atas": "action strings passed to one of the 6 unified tools above",
    "Gunakan": "Use",
    "untuk": "to",
    "cocok": "suitable for",
    "dari": "from",
    "module berbeda": "different modules",
    "= potensi": "= potential",
    "pilih": "select",
    "untuk proyek besar": "for large projects",
    "memungkinkan": "enables",
    "streaming": "streaming",
    "untuk repositori besar": "for large repositories",
    "dulu": "first",
    "untuk menemukan": "to find",
    "semua varian nama terkait": "all related name variants",
    "untuk lihat": "to see",
    "caller/callee chain": "caller/callee chain",
    "adalah": "is",
    "FTS5 relevance": "FTS5 relevance",
    "cosine similarity": "cosine similarity",
    "0-100 metric untuk readiness assessment": "0-100 metric for readiness assessment",
    "Prioritaskan": "Prioritize",
    "dengan": "with",
    "berisi": "contains",
    "saran perbaikan yang bisa langsung dieksekusi": "remediation suggestions that can be executed immediately",
    "merujuk ke": "refers to",
    "standard CODDY yang dilanggar": "CODDY standard violated",
    "cocok untuk compliance reporting": "suitable for compliance reporting",
    "dengan ISO timestamp dari audit sebelumnya": "with ISO timestamp from previous audit",
    "Selalu cek": "Always check",
    "jika": "if",
    "true": "true",
    "data dari index cache": "data from index cache",
    "instant": "instant",
    "kurang dokumentasi": "under-documented",
    "terlalu banyak komentar": "too many comments",
    "rendah": "low",
    "menandakan": "indicates",
    "arsitektur modular yang baik": "good modular architecture",
    "menandakan kode unstable": "indicates unstable code",
    "sarankan commit dulu sebelum refactor": "recommend committing before refactoring",
    "dengan": "with",
    "untuk typo-tolerant lookup": "for typo-tolerant lookup",
    "butuh": "needs",
    "dari graph node ID": "from graph node ID",
    "batasi ke modul tertentu": "limit to specific module",
    "untuk immediate neighbors": "for immediate neighbors",
    "untuk transitive": "for transitive",
    "pasti dari AST": "definitely from AST",
    "dari naming": "from naming",
    "lihat apakah 2 node di community berbeda tapi terhubung = surprising coupling": "see if 2 nodes in different communities but connected = surprising coupling",
    "independent": "independent",
    "error di satu tipe tidak menghentikan yang lain": "error in one type does not stop others",
    "partial results": "partial results",
    "perlu di-split": "needs to be split",
    "modul tidak terkait tapi saling panggil": "unrelated modules calling each other",
    "untuk direkt reporting ke user dalam format readable": "for direct reporting to user in readable format",
    "Wajib dijalankan sebelum": "Must be run before",
    "untuk repo baru": "for new repos",
    "Cache otomatis jika": "Cache automatically if",
    "panggil lagi untuk refresh": "call again to refresh",
    "memberikan overview cepat ukuran codebase dalam graph terms": "provides quick overview of codebase size in graph terms",
    "Satu tool untuk SEMUA filesystem operations": "One tool for ALL filesystem operations",
    "check": "check",
    "operation field di response": "operation field in response",
    "sinkronisasi filesystem ke database index": "filesystem to database index synchronization",
    "panggil sebelum code_analyze": "call before code_analyze",
    "untuk bulk file creation": "for bulk file creation",
    "lebih efisien daripada loop": "more efficient than looping",
    "untuk preview find-and-replace sebelum eksekusi": "to preview find-and-replace before execution",
    "untuk case-insensitive search": "for case-insensitive search",
    "untuk cari class definitions": "to find class definitions",
    "untuk lihat konteks baris yang match": "to see context of matching lines",
    "Polling-based, bukan event-driven": "Polling-based, not event-driven",
    "minimal 1 detik": "minimum 1 second",
    "Untuk long-running watch": "For long-running watch",
    "panggil berulang dengan": "call repeatedly with",
    "max_events kecil": "small max_events",
    "untuk lihat bahasa mana paling dominan": "to see which language is most dominant",
    "untuk lihat berapa banyak untracked files": "to see how many untracked files",
    "Cocok untuk pre-cleanup assessment sebelum repo_init": "Suitable for pre-cleanup assessment before repo_init",
    "Scan metadata-based": "Metadata-based scan",
    "nama file, permission, size": "file name, permission, size",
    "tidak baca konten": "does not read content",
    "= potential security leak": "= potential security leak",
    "harus segera dihandle": "must be handled immediately",
    "Panggil ini dulu sebelum tool lain untuk repo baru": "Call this first before other tools for new repos",
    "menghasilkan": "generates",
    "diperlukan tool lain": "required by other tools",
    "untuk re-index dari awal": "to re-index from scratch",
    "memberi tahu apakah clone/init berhasil": "informs whether clone/init succeeded",
    "cek": "check",
    "field": "field",
    "Jika sudah pernah di-init": "If already initialized",
    "dengan": "with",
    "ID itu langsung": "that ID directly",
    "instan meski untuk repositori besar": "instant even for large repositories",
    "Gunakan untuk fast health check": "Use for fast health check",
    "skor": "score",
    "berarti perlu indexing atau VCS setup": "means needs indexing or VCS setup",
    "memberikan churn, bus factor, bug magnets": "provides churn, bus factor, bug magnets",
    "cocok untuk code review prioritization": "suitable for code review prioritization",
    "adalah kandidat refactoring prioritas": "are refactoring priority candidates",
    "top contributor >60%": "top contributor >60%",
    "risiko knowledge silo": "knowledge silo risk",
    "Heavyweight": "Heavyweight",
    "Untuk fast check, gunakan": "For fast check, use",
    "lihat apa yang akan diindex tanpa menulis ke DB": "see what will be indexed without writing to DB",
    "menandakan apakah graph/query tool siap digunakan": "indicates whether graph/query tools are ready to use",
    "function terlalu kompleks": "function is too complex",
    "kandidat refactoring": "refactoring candidate",
    "memberikan struktur folder + symbol map lengkap": "provides complete folder structure + symbol map",
    "Zero parsing": "Zero parsing",
    "instant meski": "instant even",
    "untuk": "for",
    "auto-detect test framework dan file": "auto-detect test framework and files",
    "untuk flaky test detection + optimisation suggestions": "for flaky test detection + optimization suggestions",
    "untuk auto-generate test boilerplate dari existing source code": "to auto-generate test boilerplate from existing source code",
    "Response shape sama persis dengan module tools di atas": "Response shape identical to module tools above",
    "sama persis": "identical",
    "di atas": "above",
    "Semua Unified Tool": "All Unified Tools",
    "Yang Ingin Dilakukan": "What You Want to Do",
    "Tool yang Dipakai": "Tool to Use",
    "Key Field": "Key Field",
    "Cek kesehatan repo": "Check repo health",
    "Index repo baru": "Index new repo",
    "Search code": "Search code",
    "Analyze architecture": "Analyze architecture",
    "Audit keamanan": "Audit security",
    "Graph query": "Graph query",
    "Audit arsitektur": "Audit architecture",
    "Impact analysis": "Impact analysis",
    "Refactor": "Refactor",
    "Operasi git arbitrer": "Arbitrary git operations",
    "Operasi SVN arbitrer": "Arbitrary SVN operations",
    "Destructive": "Destructive",
    "hapus semua data": "delete all data",
    "Daftar semua repositori": "List all repositories",
    "Cek perlu re-index atau tidak": "Check if re-index needed",
    "Git/SVN history secrets scan": "Git/SVN history secrets scan",
    "VACUUM maintenance": "VACUUM maintenance",
}

# Apply translations
for indo, eng in translations.items():
    content = content.replace(indo, eng)

# Fix specific patterns that need context
content = content.replace("🧠 AI Insight:", "🧠 AI Insight:")
content = content.replace("Error codes:", "Error codes:")
content = content.replace("Success `data`:", "Success `data`:")
content = content.replace("Params:", "Params:")
content = content.replace("Operations:", "Operations:")
content = content = content.replace("Actions:", "Actions:")
content = content.replace("Success `data` (varies by operation):", "Success `data` (varies by operation):")
content = content.replace("Success `data` (multi-layer):", "Success `data` (multi-layer):")
content = content = content.replace("Success `data` (varies by query_type):", "Success `data` (varies by query_type):")
content = content.replace("Success `data` (cached or fresh):", "Success `data` (cached or fresh):")
content = content = content.replace("Success `data` (dry_run=true):", "Success `data` (dry_run=true):")
content = content.replace("Error:", "Error:")
content = content.replace("Use case:", "Use case:")
content = content.replace("Response shape sama persis dengan module tools di atas.", "Response shape identical to module tools above.")
content = content.replace("Response contract sama persis dengan module tools di atas.", "Response contract identical to module tools above.")

with open(r'C:\Users\steevenz\MCP\mcp-codecortex\docs\guides\mcp-tools-insight.md', 'w', encoding='utf-8') as f:
    f.write(content)

print('done')
