"""
@project   CodeCortex
@package   modules.idegraph.services
@author    Steeven Andrian
@copyright (c) 2026 CODDY Codework
:package:  modules.idegraph.services
:standard: CODDY-IdeGraph-v1.0

Export — Formats Engrams into Markdown and JSON for human/machine consumption.
"""

import json
import uuid
from pathlib import Path
from typing import List, Dict, Any, Optional
from src.modules.idegraph.domain.engram import Engram
from src.modules.idegraph.core.logging_service import get_logger

logger = get_logger(__name__)


class Export:
    def to_markdown(self, engram: Engram) -> str:
        lines = []
        lines.append(f"# {engram.title or 'AI Interaction Memory'}")
        lines.append(f"\n> [!NOTE]\n> **Source**: {engram.source.upper()} | **Date**: {engram.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n")
        lines.append("## Context")
        lines.append(f"- **ID**: `{engram.id}`")
        if engram.project_path:
            lines.append(f"- **Project**: `{engram.project_path}`")
        if engram.model:
            lines.append(f"- **Model**: `{engram.model}`")
        lines.append(f"- **Source File**: `{engram.source_file}`")
        if engram.ide_info:
            lines.append(f"- **IDE Name**: `{engram.ide_info.name}`")
            lines.append(f"- **IDE Type**: `{engram.ide_info.type}`")
            if engram.ide_info.installation_path:
                lines.append(f"- **Installation Path**: `{engram.ide_info.installation_path}`")
            if engram.ide_info.version:
                lines.append(f"- **IDE Version**: `{engram.ide_info.version}`")
        lines.append("\n---\n")
        lines.append("## Conversation")
        for msg in engram.messages:
            role_emoji = "\U0001f464" if msg.role == "user" else "\U0001f916"
            role_name = "USER" if msg.role == "user" else "ASSISTANT"
            lines.append(f"### {role_emoji} {role_name}")
            if msg.timestamp:
                lines.append(f"*Recorded at: {msg.timestamp}*")
            lines.append(f"\n{msg.content}\n")
            if msg.tool_use:
                lines.append("#### \U0001f6e0 Tools Used")
                for tool in msg.tool_use:
                    tool_input = tool.get('input') or ""
                    lines.append(f"- **{tool.get('name')}**: `{str(tool_input)[:200]}`")
                lines.append("")
            if msg.diffs:
                lines.append("#### \U0001f4dd Code Changes")
                for diff in msg.diffs:
                    lines.append(f"```diff\n{diff.get('patch', '')}\n```")
                lines.append("")
            lines.append("---\n")
        return "\n".join(lines)

    def export_project_report(self, project_name: str, engrams: List[Engram], output_path: Path) -> None:
        from collections import Counter
        lines = [f"# Project Report: {project_name}", f"\n*Generated by CodeCortex on {Path.cwd()}*\n"]
        lines.append(f"Total Interactions: **{len(engrams)}**\n")
        ide_counts = Counter()
        type_counts = Counter()
        for e in engrams:
            ide_name = e.ide_info.name if e.ide_info else e.source
            ide_type = e.ide_info.type if e.ide_info else 'unknown'
            ide_counts[ide_name] += 1
            type_counts[ide_type] += 1
        if ide_counts:
            lines.append("## IDE Source Summary")
            for name, count in ide_counts.most_common():
                lines.append(f"- **{name}**: {count}")
            lines.append("")
            lines.append("### By Type")
            for t, count in type_counts.most_common():
                lines.append(f"- **{t}**: {count}")
            lines.append("\n---\n")
        sorted_engrams = sorted(engrams, key=lambda e: e.created_at)
        lines.append("## Table of Contents")
        for i, engram in enumerate(sorted_engrams, 1):
            title = engram.title or f"Interaction {i}"
            lines.append(f"{i}. [{title}](#{engram.id})")
        lines.append("\n---\n")
        for engram in sorted_engrams:
            lines.append(f"<a name=\"{engram.id}\"></a>")
            lines.append(self.to_markdown(engram))
            lines.append("\n<p align=\"right\"><a href=\"#top\">\u2191 Back to top</a></p>\n")
            lines.append("\n---\n")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding='utf-8')
        logger.info(f"Project report exported to {output_path}")

    def save_json(self, engrams: List[Engram], output_path: Path, *, request_id: Optional[str] = None, version: str = "0.1.0", api_version: str = "v1") -> None:
        rid = request_id or f"req_{uuid.uuid4()}"
        data = [engram.to_export_record(request_id=rid, version=version, api_version=api_version) for engram in engrams]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        logger.info(f"JSON data exported to {output_path}")

    def save_jsonl(self, engrams: List[Engram], output_path: Path, *, request_id: Optional[str] = None, version: str = "0.1.0", api_version: str = "v1") -> None:
        rid = request_id or f"req_{uuid.uuid4()}"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            for engram in engrams:
                f.write(json.dumps(engram.to_export_record(request_id=rid, version=version, api_version=api_version), ensure_ascii=False) + '\n')
        logger.info(f"JSONL data exported to {output_path} ({len(engrams)} records)")
